name: Update README

on:
  schedule:
    # Menjalankan workflow setiap hari pukul 12 siang UTC
    - cron: "0 12 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # Checkout repositori
    - uses: actions/checkout@v4

    # Update README.md dengan data baru
    - name: Update README
      run: |
        echo '{
          "name": "Yogawan Aditya Pratama",
          "education": "University of Technology Yogyakarta",
          "interest": ["Bitcoin", "JKT48"],
          "skills": {
            "Graphic Designer": ["Figma", "CorelDraw"],
            "UI Designer": ["Figma", "Sketch"],
            "Front-End": ["Saas", "Tailwind (On-Going)", "ReactJS", "NextJS (On-Going)"],
            "Back-End": ["MonggoDB", "ExpressJS", "MySQL"]
          },
          "updated_at": "'$(date -u)'"
        }' > README.md

    # Commit dan push perubahan
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README automatically"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
